//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by array_vk.rc

#define IDR_MAINFRAME							100
#define IDC_ARRAYVK								101
#define IDI_SMALL								102
#define IDI_ARRAYVK								103
#define IDD_ARRAYVK_DIALOG						104
#define IDM_CREDITS								105
#define IDD_CREDITSBOX							106
#define IDM_EXIT								107
#define IDC_MYICON								108

#define IDM_RUN_ALL_SORTS						227
#define IDM_SELECTION_SORT						228
#define IDM_INSERTION_SORT						229
#define IDM_BUBBLE_SORT							230
#define IDM_STD_SORT_HEAP						231
#define IDM_STD_STABLE_SORT						232
#define IDM_STD_SORT							233
#define IDM_GRAIL_SORT							234
#define IDM_GRAIL_SORT_STATIC					235
#define IDM_GRAIL_SORT_CPP						236
#define IDM_GRAIL_SORT_CPP_STATIC				237
#define IDM_BITONIC_SORT						238
#define IDM_ODD_EVEN_MERGE_SORT					239
#define IDM_FOLD_SORT							240
#define IDM_STD_INPLACE_MERGE_SORT				241
#define IDM_MSD_RADIX_SORT_256					242
#define IDM_LSD_RADIX_SORT_256					243
#define IDM_AMERICAN_FLAG_SORT_256				244

#define IDM_PAUSE_SIMULATION					539
#define IDM_RESUME_SIMULATION					540
#define IDM_ABORT_SIMULATION					541

#define IDM_INITIALIZE_ALREADY_SORTED			600
#define IDM_INITIALIZE_REVERSED					601
#define IDM_INITIALIZE_ORGAN_PIPE_LINEAR		602
#define IDM_INITIALIZE_SHUFFLED					603
#define IDM_INITIALIZE_ROMUDUOJR				604


#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
